version: "3.9"

services:
  app:
    container_name: alice-web-app
    image: alice-web-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"
